version: "3.9"
   
services:
  db:
    container_name: mnecas_db
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./10-init-db.sql:/docker-entrypoint-initdb.d/10-init-db.sql
    ports:
      - 5432:5432
  web:
    container_name: mnecas_web
    build: .
    command: 
      - /bin/bash
      - -c
      - |
        python manage.py migrate --database=prod
        python manage.py create_admin
        python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=bpc_bds_db
      - POSTGRES_USER=bds_user
      - POSTGRES_PASSWORD=mnecas
    depends_on:
      mnecas_db
