# Generated by Django 3.2.9 on 2021-11-21 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211121_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydish',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_dish', to='main.delivery'),
        ),
    ]
