# Generated by Django 3.2.9 on 2021-11-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_deliverydish_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
