# Generated by Django 3.2.9 on 2021-11-25 13:09

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211125_1251'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
