# Generated by Django 3.2.9 on 2021-11-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_person_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
            ],
        ),
    ]
