# Generated by Django 3.2.9 on 2021-11-25 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_person_person_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.persontype'),
        ),
    ]
